# - Este es un "falso target" llamado "clean"
# - No va a funcionar de manera correcta..
# (porque en el directorio existe apropósito un archivo "clean")
#
# clean:
#		rm *.o

# La manera correcta sería creando un "target ficticio" con "PHONY"
.PHONY: clean
clean:
	rm *.o
