* Pregunta 1
*El estado suspendido sirve para*

Respuesta:
Un proceso que esta siendo depurado.
* Pregunta 2
*La imagen de un proceso puede estar ubicada en memoria cuando su estado es*

Respuesta:
Bloqueado
* Pregunta 3
*Un process switch implica*

Respuesta:
Dos cambios de modo
* En el PCB se guarda el estado de los registros del procesador mientras
  a. El proceso está en estado ejecutando. 
  b. Ninguna de las anteriores.
  c. El proceso no está en estado ejecutando.
** Respuesta Elegida
   a. El proceso está en estado ejecutando. 
** Respuesta Correcta
c. El proceso no está en estado ejecutando.
* Un cambio de proceso puedo ocurrir cuando
  a. Ninguna de las anteriores.
  b. Luego de realizar una llamada al sistema haya un cambio de modo. 
  c. Luego de una atender una interrupción haya un cambio de modo.
  d. Luego de realizar una llamada al sistema ejecute el mismo proceso.

** Respuesta elegida
   b. Luego de realizar una llamada al sistema haya un cambio de modo. 

   *Observaciones:*
   Una sycall seguido de un switch mode, no implica que siempre 
   haya un cambio de proceso.
   Porque un proceso puede hacer =write()= o =read()= e 
   
** Respuesta correcta
   a. Ninguna de las anteriores.






