# - impimirá por pantalla el nombre del target!
# - el @ antes del echo es para no imprimir el comando echo,
# permite que se imprima solo el mensaje que el echo quiere imprimir
# - el $@ es la MACRO AUTOMATICA :) obtendrá el nombre del target
# es decir "unprograma"
unprograma:
	@echo "el target se llama: " $@
